"""Module for machine learning visualization utilities."""

from typing import Optional, Union
import matplotlib.pyplot as plt
import numpy as np
import numpy.typing as npt
import pandas as pd
import seaborn as sns
from sklearn.metrics import auc, confusion_matrix, roc_curve


def compute_auroc_and_build_roc(
    pipeline: object,
    inputs: Union[pd.DataFrame, npt.NDArray],
    targets: Union[pd.Series, npt.NDArray],
    name: str = "",
) -> float:
    """Computes AUROC metric and plots the Receiver Operating Characteristic (ROC) curve.

    Args:
        pipeline: Fitted estimator or Scikit-Learn Pipeline object implementing `predict_proba`.
        inputs: Input features for evaluation (DataFrame or NumPy array).
        targets: Ground truth binary target labels (Series or NumPy array).
        name: Optional name prefix for plot title and console output. Defaults to "".

    Returns:
        float: Computed Area Under the ROC Curve (AUROC) score.
    """
    # Predict probabilities for positive class (1)
    y_pred_proba = pipeline.predict_proba(inputs)[:, 1]

    # Compute ROC curve metrics
    fpr, tpr, _ = roc_curve(targets, y_pred_proba, pos_label=1)

    # Compute AUROC
    roc_auc: float = float(auc(fpr, tpr))
    print(f"AUROC for {name}: {roc_auc:.2f}")

    # Plot the ROC curve
    plt.figure()
    plt.plot(
        fpr,
        tpr,
        color="darkorange",
        lw=2,
        label=f"ROC curve (area = {roc_auc:.2f})",
    )
    plt.plot([0, 1], [0, 1], color="navy", lw=2, linestyle="--")
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title(
        f"Receiver Operating Characteristic (ROC) Curve for {name}".strip()
    )
    plt.legend(loc="lower right")
    plt.show()

    return roc_auc


def predict_and_plot(
    targets_predicted: Union[pd.Series, npt.NDArray],
    targets: Union[pd.Series, npt.NDArray],
    name: str = "",
) -> npt.NDArray:
    """Plots a normalized confusion matrix heatmap for model predictions.

    Args:
        targets_predicted: Predicted class labels generated by the model.
        targets: True target values/ground truth labels.
        name: Optional model/experiment name prefix for the title. Defaults to "".

    Returns:
        npt.NDArray: The calculated normalized confusion matrix array.
    """
    cf = confusion_matrix(targets, targets_predicted, normalize="true")

    plt.figure()
    sns.heatmap(cf, annot=True, cmap="Blues")
    plt.xlabel("Prediction")
    plt.ylabel("Target")

    title = f"{name} Confusion Matrix".strip()
    plt.title(title)
    plt.show()

    return cf